plugins {
    id 'java'
}

group = 'Darius'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    // https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-core
    implementation 'org.apache.logging.log4j:log4j-core:2.24.3'
    // https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-api
    implementation 'org.apache.logging.log4j:log4j-api:2.24.3'
    // https://mvnrepository.com/artifact/org.xerial/sqlite-jdbc
    implementation group: 'org.xerial', name: 'sqlite-jdbc', version: '3.49.1.0'

    implementation 'org.hibernate.orm:hibernate-core:7.0.0.CR1'
    implementation 'org.hibernate.validator:hibernate-validator:9.0.0.CR1'
    implementation 'org.glassfish:jakarta.el:4.0.2'
    implementation 'org.hibernate.orm:hibernate-community-dialects:7.0.0.CR1'
    implementation 'org.springframework:spring-context:6.1.1'

    implementation project(":Model")
    implementation project(":Utils")
}

test {
    useJUnitPlatform()
}