package Darius.rpcprotocol;

public enum RequestType {
    LOGIN, LOGOUT, GET_AGE_GROUPS, GET_EVENTS, GET_CHILDREN, ADD_CHILDREN, ADD_REGISTER, GET_REGISTRATION_BY_PERSON,
    GET_ONE_AGE_GROUP_BY_AGE, GET_CHILD_BY_CNP
}
