package Darius.rpcprotocol;

public enum ResponseType {
    OK, ERROR, LOGGED, GET_AGE_GROUPS, GET_EVENTS, GET_CHILDREN, GET_REGISTRATION_BY_PERSON,
    GET_ONE_AGE_GROUP, GET_CHILD_BY_CNP, REGISTRATION_SAVED
}
