jakarta.persistence.jdbc.driver=org.sqlite.JDBC
jakarta.persistence.jdbc.url=jdbc:sqlite:D:\\Scoala\\an2\\Sem2\\MPP\\adsa\\untitled\\src\\main\\resources\\database\\concurs.db
jakarta.persistence.schema-generation.database.action=update
jakarta.persistence.schema-generation.foreign-keys=true
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true